import chromium from '@sparticuz/chromium'
import puppeteer from 'puppeteer-core'

interface ScanData {
  id: string
  url: string
  score: number
  grade: string
  findings: {
    severity: string
    title: string
    category: string
    description?: string
    remediation?: string
  }[]
  categoryScores: { category: string; score: number }[]
  completedAt?: string | Date
}

function getSeverityColor(severity: string): string {
  const map: Record<string, string> = {
    CRITICAL: '#ef4444',
    HIGH: '#f59e0b',
    MEDIUM: '#f97316',
    LOW: '#60a5fa',
    INFO: '#8888aa',
  }
  return map[severity] ?? '#8888aa'
}

function getGradeColor(score: number): string {
  if (score >= 80) return '#4ade80'
  if (score >= 60) return '#f59e0b'
  return '#ef4444'
}

function buildHtml(scan: ScanData): string {
  const gradeColor = getGradeColor(scan.score)
  const date = scan.completedAt
    ? new Date(scan.completedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString()

  const severityCounts = scan.findings.reduce((acc, f) => {
    acc[f.severity] = (acc[f.severity] ?? 0) + 1
    return acc
  }, {} as Record<string, number>)

  const findingRows = scan.findings
    .slice(0, 50)
    .map(f => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #1e1e35;">
          <span style="display:inline-block;padding:2px 6px;border-radius:4px;font-size:10px;font-weight:700;background:${getSeverityColor(f.severity)}20;color:${getSeverityColor(f.severity)};border:1px solid ${getSeverityColor(f.severity)}40;">
            ${f.severity}
          </span>
        </td>
        <td style="padding:8px 12px;border-bottom:1px solid #1e1e35;color:#f0f0ff;font-size:12px;">${f.title}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #1e1e35;color:#8888aa;font-size:11px;">${f.category}</td>
      </tr>
    `).join('')

  const categoryRows = scan.categoryScores.map(cs => {
    const col = cs.score >= 80 ? '#4ade80' : cs.score >= 60 ? '#f59e0b' : '#ef4444'
    return `
      <div style="margin-bottom:10px;">
        <div style="display:flex;justify-content:space-between;margin-bottom:4px;">
          <span style="font-size:11px;color:#8888aa;">${cs.category}</span>
          <span style="font-size:11px;font-weight:700;color:${col};">${cs.score}</span>
        </div>
        <div style="height:4px;background:#1e1e35;border-radius:2px;overflow:hidden;">
          <div style="height:100%;width:${cs.score}%;background:${col};border-radius:2px;"></div>
        </div>
      </div>
    `
  }).join('')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #050508; color: #f0f0ff; font-family: 'DM Mono', 'Courier New', monospace; padding: 40px; }
    h1, h2, h3 { font-family: 'Chakra Petch', 'Arial', sans-serif; }
  </style>
</head>
<body>
  <!-- Header -->
  <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:32px;padding-bottom:20px;border-bottom:1px solid #1e1e35;">
    <div>
      <h1 style="font-size:24px;color:#4ade80;letter-spacing:0.1em;">VAULTRIX</h1>
      <p style="color:#8888aa;font-size:11px;margin-top:4px;">Security Scan Report</p>
    </div>
    <div style="text-align:right;">
      <p style="color:#8888aa;font-size:11px;">${date}</p>
      <p style="color:#3a3a5c;font-size:10px;margin-top:2px;">Generated by VAULTRIX</p>
    </div>
  </div>

  <!-- Target -->
  <div style="margin-bottom:24px;">
    <p style="font-size:11px;color:#8888aa;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:6px;">Target</p>
    <p style="font-size:16px;color:#f0f0ff;">${scan.url}</p>
  </div>

  <!-- Score & Grade -->
  <div style="display:flex;gap:24px;margin-bottom:32px;">
    <div style="background:#0d0d14;border:1px solid #1e1e35;border-radius:8px;padding:20px;flex:1;text-align:center;">
      <p style="font-size:11px;color:#8888aa;text-transform:uppercase;margin-bottom:8px;">Security Score</p>
      <p style="font-size:48px;font-weight:700;color:${gradeColor};">${scan.score}</p>
    </div>
    <div style="background:#0d0d14;border:1px solid #1e1e35;border-radius:8px;padding:20px;flex:1;text-align:center;">
      <p style="font-size:11px;color:#8888aa;text-transform:uppercase;margin-bottom:8px;">Grade</p>
      <p style="font-size:48px;font-weight:700;color:${gradeColor};">${scan.grade ?? '?'}</p>
    </div>
    <div style="background:#0d0d14;border:1px solid #1e1e35;border-radius:8px;padding:20px;flex:1;text-align:center;">
      <p style="font-size:11px;color:#8888aa;text-transform:uppercase;margin-bottom:8px;">Total Findings</p>
      <p style="font-size:48px;font-weight:700;color:#f0f0ff;">${scan.findings.length}</p>
    </div>
    <div style="background:#0d0d14;border:1px solid #1e1e35;border-radius:8px;padding:20px;flex:1;text-align:center;">
      <p style="font-size:11px;color:#8888aa;text-transform:uppercase;margin-bottom:8px;">Critical</p>
      <p style="font-size:48px;font-weight:700;color:#ef4444;">${severityCounts['CRITICAL'] ?? 0}</p>
    </div>
  </div>

  <!-- Category Scores -->
  ${scan.categoryScores.length > 0 ? `
  <div style="background:#0d0d14;border:1px solid #1e1e35;border-radius:8px;padding:20px;margin-bottom:24px;">
    <h3 style="font-size:13px;color:#f0f0ff;margin-bottom:16px;text-transform:uppercase;letter-spacing:0.1em;">Category Scores</h3>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:0 32px;">
      ${categoryRows}
    </div>
  </div>
  ` : ''}

  <!-- Findings Table -->
  ${scan.findings.length > 0 ? `
  <div style="margin-top:8px;">
    <h3 style="font-size:13px;color:#f0f0ff;margin-bottom:12px;text-transform:uppercase;letter-spacing:0.1em;">Findings</h3>
    <table style="width:100%;border-collapse:collapse;background:#0d0d14;border:1px solid #1e1e35;border-radius:8px;overflow:hidden;">
      <thead>
        <tr style="border-bottom:1px solid #1e1e35;">
          <th style="padding:8px 12px;text-align:left;font-size:10px;color:#3a3a5c;text-transform:uppercase;letter-spacing:0.1em;">Severity</th>
          <th style="padding:8px 12px;text-align:left;font-size:10px;color:#3a3a5c;text-transform:uppercase;letter-spacing:0.1em;">Finding</th>
          <th style="padding:8px 12px;text-align:left;font-size:10px;color:#3a3a5c;text-transform:uppercase;letter-spacing:0.1em;">Category</th>
        </tr>
      </thead>
      <tbody>${findingRows}</tbody>
    </table>
    ${scan.findings.length > 50 ? `<p style="font-size:11px;color:#3a3a5c;margin-top:8px;">… and ${scan.findings.length - 50} more findings</p>` : ''}
  </div>
  ` : ''}

  <!-- Footer -->
  <div style="margin-top:40px;padding-top:20px;border-top:1px solid #1e1e35;text-align:center;">
    <p style="font-size:10px;color:#3a3a5c;">VAULTRIX — Enterprise Web Security Scanner — Confidential</p>
    <p style="font-size:10px;color:#3a3a5c;margin-top:4px;">Results are point-in-time. Re-scan regularly to monitor your security posture.</p>
  </div>
</body>
</html>
`
}

export async function generateScanPdf(scan: ScanData): Promise<Buffer> {
  const isLocal = process.env.NODE_ENV === 'development'

  let browser
  if (isLocal) {
    // Local: use system Chrome or installed puppeteer
    browser = await puppeteer.launch({
      executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    })
  } else {
    // Production (Vercel): use @sparticuz/chromium
    browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: true,
    })
  }

  try {
    const page = await browser.newPage()
    await page.setContent(buildHtml(scan), { waitUntil: 'networkidle0' })
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '0', right: '0', bottom: '0', left: '0' },
    })
    return Buffer.from(pdf)
  } finally {
    await browser.close()
  }
}
